[package]
name = "evm"
version = "0.0.1"
edition = "2018"
authors = ["arnaucube <root@arnaucube.com>"]
license = "GPL-3.0"
repository = "https://github.com/arnaucube/evm-rs"

[dependencies]
num = "0.4.0"
num-traits = "0.2.14"
num-bigint = "0.4"
hex = "0.4.3"
