[package]
name = "evm"
version = "0.0.1"
edition = "2018"
authors = ["arnaucube <root@arnaucube.com>"]
license = "GPL-3.0"
repository = "https://github.com/arnaucube/evm-rs"

[dependencies]
num-bigint = "0.4"
num = "0.4.0"
hex = "0.4.3"
